/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/__root'
import { Route as PayloadRouteImport } from './app/_payload'
import { Route as FrontendRouteImport } from './app/_frontend'
import { Route as FrontendIndexRouteImport } from './app/_frontend/index'
import { Route as FrontendSearchRouteImport } from './app/_frontend/search'
import { Route as FrontendSlugRouteImport } from './app/_frontend/$slug'
import { Route as PayloadAdminIndexRouteImport } from './app/_payload/admin.index'
import { Route as FrontendPostsIndexRouteImport } from './app/_frontend/posts.index'
import { Route as PayloadApiServerFunctionRouteImport } from './app/_payload/api.server-function'
import { Route as PayloadApiSplatRouteImport } from './app/_payload/api.$'
import { Route as PayloadAdminSplatRouteImport } from './app/_payload/admin.$'
import { Route as FrontendPostsSlugRouteImport } from './app/_frontend/posts.$slug'
import { Route as FrontendPostsPagePageNumberRouteImport } from './app/_frontend/posts_.page.$pageNumber'

const PayloadRoute = PayloadRouteImport.update({
  id: '/_payload',
  getParentRoute: () => rootRouteImport,
} as any)
const FrontendRoute = FrontendRouteImport.update({
  id: '/_frontend',
  getParentRoute: () => rootRouteImport,
} as any)
const FrontendIndexRoute = FrontendIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FrontendRoute,
} as any)
const FrontendSearchRoute = FrontendSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => FrontendRoute,
} as any)
const FrontendSlugRoute = FrontendSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => FrontendRoute,
} as any)
const PayloadAdminIndexRoute = PayloadAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => PayloadRoute,
} as any)
const FrontendPostsIndexRoute = FrontendPostsIndexRouteImport.update({
  id: '/posts/',
  path: '/posts/',
  getParentRoute: () => FrontendRoute,
} as any)
const PayloadApiServerFunctionRoute =
  PayloadApiServerFunctionRouteImport.update({
    id: '/api/server-function',
    path: '/api/server-function',
    getParentRoute: () => PayloadRoute,
  } as any)
const PayloadApiSplatRoute = PayloadApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => PayloadRoute,
} as any)
const PayloadAdminSplatRoute = PayloadAdminSplatRouteImport.update({
  id: '/admin/$',
  path: '/admin/$',
  getParentRoute: () => PayloadRoute,
} as any)
const FrontendPostsSlugRoute = FrontendPostsSlugRouteImport.update({
  id: '/posts/$slug',
  path: '/posts/$slug',
  getParentRoute: () => FrontendRoute,
} as any)
const FrontendPostsPagePageNumberRoute =
  FrontendPostsPagePageNumberRouteImport.update({
    id: '/posts_/page/$pageNumber',
    path: '/posts/page/$pageNumber',
    getParentRoute: () => FrontendRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof FrontendIndexRoute
  '/$slug': typeof FrontendSlugRoute
  '/search': typeof FrontendSearchRoute
  '/posts/$slug': typeof FrontendPostsSlugRoute
  '/admin/$': typeof PayloadAdminSplatRoute
  '/api/$': typeof PayloadApiSplatRoute
  '/api/server-function': typeof PayloadApiServerFunctionRoute
  '/posts/': typeof FrontendPostsIndexRoute
  '/admin/': typeof PayloadAdminIndexRoute
  '/posts/page/$pageNumber': typeof FrontendPostsPagePageNumberRoute
}
export interface FileRoutesByTo {
  '/': typeof FrontendIndexRoute
  '/$slug': typeof FrontendSlugRoute
  '/search': typeof FrontendSearchRoute
  '/posts/$slug': typeof FrontendPostsSlugRoute
  '/admin/$': typeof PayloadAdminSplatRoute
  '/api/$': typeof PayloadApiSplatRoute
  '/api/server-function': typeof PayloadApiServerFunctionRoute
  '/posts': typeof FrontendPostsIndexRoute
  '/admin': typeof PayloadAdminIndexRoute
  '/posts/page/$pageNumber': typeof FrontendPostsPagePageNumberRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_frontend': typeof FrontendRouteWithChildren
  '/_payload': typeof PayloadRouteWithChildren
  '/_frontend/$slug': typeof FrontendSlugRoute
  '/_frontend/search': typeof FrontendSearchRoute
  '/_frontend/': typeof FrontendIndexRoute
  '/_frontend/posts/$slug': typeof FrontendPostsSlugRoute
  '/_payload/admin/$': typeof PayloadAdminSplatRoute
  '/_payload/api/$': typeof PayloadApiSplatRoute
  '/_payload/api/server-function': typeof PayloadApiServerFunctionRoute
  '/_frontend/posts/': typeof FrontendPostsIndexRoute
  '/_payload/admin/': typeof PayloadAdminIndexRoute
  '/_frontend/posts_/page/$pageNumber': typeof FrontendPostsPagePageNumberRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$slug'
    | '/search'
    | '/posts/$slug'
    | '/admin/$'
    | '/api/$'
    | '/api/server-function'
    | '/posts/'
    | '/admin/'
    | '/posts/page/$pageNumber'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$slug'
    | '/search'
    | '/posts/$slug'
    | '/admin/$'
    | '/api/$'
    | '/api/server-function'
    | '/posts'
    | '/admin'
    | '/posts/page/$pageNumber'
  id:
    | '__root__'
    | '/_frontend'
    | '/_payload'
    | '/_frontend/$slug'
    | '/_frontend/search'
    | '/_frontend/'
    | '/_frontend/posts/$slug'
    | '/_payload/admin/$'
    | '/_payload/api/$'
    | '/_payload/api/server-function'
    | '/_frontend/posts/'
    | '/_payload/admin/'
    | '/_frontend/posts_/page/$pageNumber'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  FrontendRoute: typeof FrontendRouteWithChildren
  PayloadRoute: typeof PayloadRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_payload': {
      id: '/_payload'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PayloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_frontend': {
      id: '/_frontend'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof FrontendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_frontend/': {
      id: '/_frontend/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof FrontendIndexRouteImport
      parentRoute: typeof FrontendRoute
    }
    '/_frontend/search': {
      id: '/_frontend/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof FrontendSearchRouteImport
      parentRoute: typeof FrontendRoute
    }
    '/_frontend/$slug': {
      id: '/_frontend/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof FrontendSlugRouteImport
      parentRoute: typeof FrontendRoute
    }
    '/_payload/admin/': {
      id: '/_payload/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof PayloadAdminIndexRouteImport
      parentRoute: typeof PayloadRoute
    }
    '/_frontend/posts/': {
      id: '/_frontend/posts/'
      path: '/posts'
      fullPath: '/posts/'
      preLoaderRoute: typeof FrontendPostsIndexRouteImport
      parentRoute: typeof FrontendRoute
    }
    '/_payload/api/server-function': {
      id: '/_payload/api/server-function'
      path: '/api/server-function'
      fullPath: '/api/server-function'
      preLoaderRoute: typeof PayloadApiServerFunctionRouteImport
      parentRoute: typeof PayloadRoute
    }
    '/_payload/api/$': {
      id: '/_payload/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof PayloadApiSplatRouteImport
      parentRoute: typeof PayloadRoute
    }
    '/_payload/admin/$': {
      id: '/_payload/admin/$'
      path: '/admin/$'
      fullPath: '/admin/$'
      preLoaderRoute: typeof PayloadAdminSplatRouteImport
      parentRoute: typeof PayloadRoute
    }
    '/_frontend/posts/$slug': {
      id: '/_frontend/posts/$slug'
      path: '/posts/$slug'
      fullPath: '/posts/$slug'
      preLoaderRoute: typeof FrontendPostsSlugRouteImport
      parentRoute: typeof FrontendRoute
    }
    '/_frontend/posts_/page/$pageNumber': {
      id: '/_frontend/posts_/page/$pageNumber'
      path: '/posts/page/$pageNumber'
      fullPath: '/posts/page/$pageNumber'
      preLoaderRoute: typeof FrontendPostsPagePageNumberRouteImport
      parentRoute: typeof FrontendRoute
    }
  }
}

interface FrontendRouteChildren {
  FrontendSlugRoute: typeof FrontendSlugRoute
  FrontendSearchRoute: typeof FrontendSearchRoute
  FrontendIndexRoute: typeof FrontendIndexRoute
  FrontendPostsSlugRoute: typeof FrontendPostsSlugRoute
  FrontendPostsIndexRoute: typeof FrontendPostsIndexRoute
  FrontendPostsPagePageNumberRoute: typeof FrontendPostsPagePageNumberRoute
}

const FrontendRouteChildren: FrontendRouteChildren = {
  FrontendSlugRoute: FrontendSlugRoute,
  FrontendSearchRoute: FrontendSearchRoute,
  FrontendIndexRoute: FrontendIndexRoute,
  FrontendPostsSlugRoute: FrontendPostsSlugRoute,
  FrontendPostsIndexRoute: FrontendPostsIndexRoute,
  FrontendPostsPagePageNumberRoute: FrontendPostsPagePageNumberRoute,
}

const FrontendRouteWithChildren = FrontendRoute._addFileChildren(
  FrontendRouteChildren,
)

interface PayloadRouteChildren {
  PayloadAdminSplatRoute: typeof PayloadAdminSplatRoute
  PayloadApiSplatRoute: typeof PayloadApiSplatRoute
  PayloadApiServerFunctionRoute: typeof PayloadApiServerFunctionRoute
  PayloadAdminIndexRoute: typeof PayloadAdminIndexRoute
}

const PayloadRouteChildren: PayloadRouteChildren = {
  PayloadAdminSplatRoute: PayloadAdminSplatRoute,
  PayloadApiSplatRoute: PayloadApiSplatRoute,
  PayloadApiServerFunctionRoute: PayloadApiServerFunctionRoute,
  PayloadAdminIndexRoute: PayloadAdminIndexRoute,
}

const PayloadRouteWithChildren =
  PayloadRoute._addFileChildren(PayloadRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  FrontendRoute: FrontendRouteWithChildren,
  PayloadRoute: PayloadRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
